add_newline = false

right_format = """\
$kubernetes\
$aws\
$time\
"""

[directory]
truncation_length = 1

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
truncation_length = 25
symbol = 'ï˜ '

[aws]
format = '( [($profile)(\[$duration\])]($style))'
expiration_symbol = ' ï‘§'

[docker_context]
disabled = true

[kubernetes]
format = ' [$symbol$context]($style)'
symbol = 'ó±ƒ¾ '
disabled = false

[helm]
symbol = 'ğŸ“¦ '

[terraform]
format = ' [$symbol($version)]($style)'
symbol = 'ó±¢ '
disabled = true

[time]
format = ' [$time]($style)'
style = 'bold green'
disabled = false

[package]
disabled = true

[dart]
disabled = true

[nodejs]
format = ' [$symbol($version)]($style)'
disabled = true

[cmd_duration]
disabled = true
min_time = 10_000 # ms

[line_break]
disabled = true

